# Generated by Django 5.2 on 2025-04-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reset_and_populate_predefined_pairs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcolor',
            name='confidence_score',
        ),
        migrations.AlterUniqueTogether(
            name='predefinedpair',
            unique_together=set(), 
        ),
    ]
