# Generated by Django 5.2 on 2025-04-24 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_itemcolor_confidence_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalselection',
            options={},
        ),
        migrations.RemoveField(
            model_name='finalselection',
            name='match_strength',
        ),
    ]
